spring:
  application:
    name: trainer-contribution-calculator

  data:
    mongodb:
      uri: mongodb+srv://${mongo_user}:${mongo_password}@clusterforlearning.6xlkro2.mongodb.net/?retryWrites=true&w=majority&appName=ClusterForLearning
      database: trainer_contribution_db
      auto-index-creation: true

server:
  port: 7575

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    instances:
      trainerHoursCircuitBreaker:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        minimum-number-of-calls: 6
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      trainerHoursCircuitBreaker:
        timeout-duration: 2s

logging:
  level:
    root: INFO
    com.mygym.crm.trainercontributioncalculator: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: TrainerContributionCalculator/logs/trainer-contribution-calculator.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 30

logback:
  appender:
    file:
      file: ${logging.file.name}
      encoder:
        pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      filter:
        expression: "logger.name.startsWith('com.mygym.crm.trainercontributioncalculator')"